/**
 * Code Generation
 * Converts JavaScript to TypeScript with type annotations
 */
class CodeGenerator {
  generateTypeScript(ast, typeInfo) {
    let tsCode = '// Generated by CodeMorph Lite\n';
    tsCode += '// TypeScript conversion\n\n';
    
    tsCode += this.generateFromAST(ast, typeInfo);
    
    return tsCode;
  }

  generateFromAST(node, typeInfo, indent = 0) {
    if (!node) return '';
    
    const indentStr = '  '.repeat(indent);
    
    switch (node.type) {
      case 'File':
        return this.generateFromAST(node.program, typeInfo, indent);
        
      case 'Program':
        return node.body.map(child => this.generateFromAST(child, typeInfo, indent)).join('\n');
        
      case 'VariableDeclaration':
        const declarations = node.declarations.map(decl => {
          let type = typeInfo[decl.id.name] || 'any';
          let value = decl.init ? this.generateFromAST(decl.init, typeInfo, 0) : '';
          return `${decl.id.name}: ${type}${value ? ` = ${value}` : ''}`;
        }).join(', ');
        return `${indentStr}${node.kind} ${declarations};`;
        
      case 'FunctionDeclaration':
        const params = node.params.map(param => {
          let type = typeInfo[param.name] || 'any';
          return `${param.name}: ${type}`;
        }).join(', ');
        const returnType = this.inferReturnType(node, typeInfo);
        const body = this.generateFromAST(node.body, typeInfo, indent + 1);
        return `${indentStr}function ${node.id.name}(${params}): ${returnType} {\n${body}\n${indentStr}}`;
        
      case 'BlockStatement':
        return node.body.map(child => this.generateFromAST(child, typeInfo, indent)).join('\n');
        
      case 'ReturnStatement':
        const value = node.argument ? this.generateFromAST(node.argument, typeInfo, 0) : '';
        return `${indentStr}return${value ? ` ${value}` : ''};`;
        
      case 'NumericLiteral':
        return node.value.toString();
        
      case 'StringLiteral':
        return `"${node.value}"`;
        
      case 'Identifier':
        return node.name;
        
      case 'CallExpression':
        const callee = this.generateFromAST(node.callee, typeInfo, 0);
        const args = node.arguments.map(arg => this.generateFromAST(arg, typeInfo, 0)).join(', ');
        return `${callee}(${args})`;
        
      case 'MemberExpression':
        const obj = this.generateFromAST(node.object, typeInfo, 0);
        const prop = node.property.name;
        return `${obj}.${prop}`;
        
      case 'ExpressionStatement':
        return `${indentStr}${this.generateFromAST(node.expression, typeInfo, 0)};`;
        
      case 'BinaryExpression':
        const left = this.generateFromAST(node.left, typeInfo, 0);
        const right = this.generateFromAST(node.right, typeInfo, 0);
        return `${left} ${node.operator} ${right}`;
        
      default:
        return '';
    }
  }

  inferReturnType(node, typeInfo) {
    // Simple return type inference
    let hasReturn = false;
    let returnType = 'void';
    
    const checkReturn = (n) => {
      if (n.type === 'ReturnStatement' && n.argument) {
        hasReturn = true;
        if (n.argument.type === 'NumericLiteral') returnType = 'number';
        else if (n.argument.type === 'StringLiteral') returnType = 'string';
        else returnType = 'any';
      }
      if (n.body) {
        if (Array.isArray(n.body)) n.body.forEach(checkReturn);
        else checkReturn(n.body);
      }
    };
    
    checkReturn(node);
    return hasReturn ? returnType : 'void';
  }
}

module.exports = CodeGenerator;